In [ ]:
from mpi4py import MPI
import numpy as np

comm = MPI.COMM_WORLD
rank = comm.Get_rank()
size = comm.Get_size()

amode = MPI.MODE_WRONLY|MPI.MODE_CREATE
fh = MPI.File.Open(comm, "noncontiginious", amode)

item_count = 10

buffer = np.empty(item_count, dtype='i')
buffer[:] = rank

filetype = MPI.INT.Create_vector(item_count, 1, size)
filetype.Commit()

displacement = MPI.INT.Get_size()*rank
fh.Set_view(displacement, filetype=filetype)

fh.Write_all(buffer)
filetype.Free()
fh.Close()

In [50]:
item_count = 10

for i in range(4):

    buffer = np.empty(item_count, dtype='i')
    buffer[:] = i
    print(buffer)

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[2 2 2 2 2 2 2 2 2 2]
[3 3 3 3 3 3 3 3 3 3]


In [51]:
len(buffer)

10

In [53]:
filetype = MPI.INT.Sub(item_count, 1, 4)

In [56]:
?MPI.INT.Create_vector

In [ ]:
fh.Re

In [61]:
nx, ny = 500 ,500

array = np.ones((nx,ny), dtype=np.int)

In [85]:
?MPI.FLOAT.Create_vector

In [65]:
MPI.DOUBLE.Create_vector?

In [66]:
MPI.DOUBLE.Get_size()

8

In [69]:
MPI.FLOAT.Get_size()*4

16

In [73]:
nx, ny, xL, yL, xR, yR, Imax  =500, 500, -2, -2, +2, +2, 1000

plane_coordinates = np.zeros(4, dtype='d') 
pixel_maxiter = np.zeros(3, dtype='i')

plane_coordinates[:] = [xL, xR, yL, yR]
pixel_maxiter[:] = [nx, ny, Imax]

In [87]:
MPI.DOUBLE.Get_size()

8

In [109]:
help(fh.Write_at)

Help on built-in function Write_at:

Write_at(...) method of mpi4py.MPI.File instance
    File.Write_at(self, Offset offset, buf, Status status=None)
    
    Write using explicit offset



In [110]:
help(fh.Write_at_all)

Help on built-in function Write_at_all:

Write_at_all(...) method of mpi4py.MPI.File instance
    File.Write_at_all(self, Offset offset, buf, Status status=None)
    
    Collective write using explicit offset



In [113]:
help(fh.Set_view)

Help on built-in function Set_view:

Set_view(...) method of mpi4py.MPI.File instance
    File.Set_view(self, Offset disp=0, Datatype etype=None, Datatype filetype=None, datarep=None, Info info=INFO_NULL)
    
    Set the file view



In [132]:
help(MPI.INT.Create_subarray)

Help on built-in function Create_subarray:

Create_subarray(...) method of mpi4py.MPI.Datatype instance
    Datatype.Create_subarray(self, sizes, subsizes, starts, int order=ORDER_C)
    
    Create a datatype for a subarray of
    a regular, multidimensional array



In [134]:
help(MPI.INT.Create_darray)

Help on built-in function Create_darray:

Create_darray(...) method of mpi4py.MPI.Datatype instance
    Datatype.Create_darray(self, int size, int rank, gsizes, distribs, dargs, psizes, int order=ORDER_C)
    
    Create a datatype representing an HPF-like
    distributed array on Cartesian process grids



In [127]:
array = np.ones((nx,ny), dtype=np.int)

In [128]:
array

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [131]:
array.shape[0]

500

In [ ]:
help(MPI.INT.)

In [138]:
dir(100)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 'real',
 'to_bytes']

In [140]:
100.to_bytes()

SyntaxError: invalid syntax (<ipython-input-140-42d2c8fe0398>, line 1)

In [145]:
np.array([100],dtype=np.int).nbytes

8

In [146]:
np.array([500],dtype=np.int).nbytesarray = np.ones(nx*ny, dtype='i')

8

In [148]:
np.array([100,100,500]).nbytes

24

In [152]:
array = np.ones([nx,ny], dtype='i')

In [153]:
array

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]], dtype=int32)

In [151]:
array.reshape()

(250000,)

In [157]:
np.float64(8)

8.0